export const ALL_DESIGNATIONS = [
  'Founder',
  'Co-Founder',
  'Admin Head',
  'Finance Head',
  'HR Head',
  'Ops Head',
  'Sales Head - Field Sales',
  'Sales Head - Inside Sales',
  'Business Development Head - Field BD',
  'Business Development Head - Inside BD',
  'Regional Head - East Sales',
  'Regional Head - West Sales',
  'Regional Head - North Sales',
  'Regional Head - South Sales',
  'Regional Head - East BD',
  'Regional Head - West BD',
  'Regional Head - North BD',
  'Regional Head - South BD',
  'State Head - Sales',
  'State Head - BD',
  'District Manager - Sales',
  'District Manager - BD',
  'Debt Manager',
  'RM - Sales',
  'RM - BD',
] as const

export type Designation = (typeof ALL_DESIGNATIONS)[number]

// Hierarchy levels — lower number = higher authority
export const DESIGNATION_LEVEL: Record<string, number> = {
  'Founder': 1,
  'Co-Founder': 1,
  'Admin Head': 2,
  'Finance Head': 2,
  'HR Head': 2,
  'Ops Head': 2,
  'Sales Head - Field Sales': 2,
  'Sales Head - Inside Sales': 2,
  'Business Development Head - Field BD': 2,
  'Business Development Head - Inside BD': 2,
  'Regional Head - East Sales': 3,
  'Regional Head - West Sales': 3,
  'Regional Head - North Sales': 3,
  'Regional Head - South Sales': 3,
  'Regional Head - East BD': 3,
  'Regional Head - West BD': 3,
  'Regional Head - North BD': 3,
  'Regional Head - South BD': 3,
  'State Head - Sales': 4,
  'State Head - BD': 4,
  'District Manager - Sales': 5,
  'District Manager - BD': 5,
  'Debt Manager': 5,
  'RM - Sales': 6,
  'RM - BD': 6,
}
